name: commit

on:
  schedule:
    # checking hourly
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Commit
        run: |

          git config --local user.email "xuqingjian8@gmail.com"
          git config --local user.name "Sean Xu"
          git commit -m "`date '+Daily Commit: at %Y-%m-%d %H:%M'`"
          git push origin master