name: commit

on:
  schedule:
    # checking hourly
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Commit
        run: |

          git config --local user.email "xuqingjian@sjtu.edu.cn"
          git config --local user.name "CSeanXu"
          git commit -m "`date '+Daily Commit: at %Y-%m-%d %H:%M'`" --allow-empty
          git push origin master